In [8]:
import numpy as numpy

In [6]:
arr= numpy.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [14]:
a=[1,2,3.3,4.5]
a

[1, 2, 3.3, 4.5]

In [16]:
numpy.array(a)

array([1. , 2. , 3.3, 4.5])

In [17]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
numpy.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr= numpy.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [22]:
numpy.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])