In [8]:
import numpy as numpy

In [6]:
arr= numpy.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [14]:
a=[1,2,3.3,4.5]
a

[1, 2, 3.3, 4.5]

In [16]:
numpy.array(a)

array([1. , 2. , 3.3, 4.5])

In [17]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
numpy.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr= numpy.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [22]:
numpy.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
arr = numpy.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [31]:
numpy.random.rand(5)

array([0.42766373, 0.72041306, 0.68911251, 0.04618604, 0.98437483])

In [36]:
numpy.random.randn(100)

array([-1.07097989,  1.76517142, -0.69504309, -1.48456484, -0.64993052,
        0.18442635,  2.07236488,  0.96658776, -0.93706875,  1.62198858,
        0.44738138, -1.55303661, -0.40296524,  0.63187484, -0.56954959,
        1.69558504,  0.81540355, -1.47247057,  0.77460795, -1.49017533,
        0.54057274,  0.72656959, -2.22160428, -0.03071308, -0.3932781 ,
        0.73639527,  0.95741683, -0.47962896,  1.03491377, -0.04890756,
       -0.48858365,  0.66532105,  0.55963273, -0.53218526, -0.38401201,
        1.419607  , -0.9673058 , -0.51313878, -0.15135198,  0.80979311,
       -1.92376808, -0.09663119, -0.87075019, -0.28878837, -0.58037859,
        2.27009379, -1.64976271,  1.41815559,  0.53389322,  0.58643968,
        0.98289002, -0.23699702, -0.20721122, -0.67048457,  1.40447188,
       -0.39359112,  0.93177384, -1.04980212, -0.42928862, -0.6377856 ,
        0.53955453, -0.37288477,  0.84746589, -1.54885698,  0.25355091,
        0.80922373,  0.53212069,  0.57378596,  0.95787691, -0.23

In [40]:
numpy.random.randint(10, 100, 5)

array([87, 26, 16, 78, 38], dtype=int32)

In [42]:
arr = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr.shape

(3, 3)

In [44]:
arr.size

9

In [45]:
arr.dtype

dtype('int64')

In [46]:
arr = numpy.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [49]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])